version: '2'

services:
  app:
    image: 'example/employee-management:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: 'postgres:15.1-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=employee-management-db
      - POSTGRES_USER=app-user
      - POSTGRES_PASSWORD=app-user-pwd